name: Android CI - Build APK

on:
  workflow_dispatch:  # শুধু ম্যানুয়াল ট্রিগার
    inputs:
      build_type:
        description: 'APK Build Type'
        required: true
        default: 'debug'
        type: choice
        options:
          - debug
          - release
      version_name:
        description: 'Version Name (e.g., 1.0.0)'
        required: false
        default: '1.0.0'
      version_code:
        description: 'Version Code (e.g., 1)'
        required: false
        default: '1'

env:
  APP_NAME: "My Eye"
  PACKAGE_NAME: "com.ahamedrahim.myeye"
  ANDROID_COMPILE_SDK: "34"
  ANDROID_BUILD_TOOLS: "34.0.0"
  JAVA_VERSION: "17"

jobs:
  build:
    name: Build ${{ github.event.inputs.build_type }} APK
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup Java ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ env.JAVA_VERSION }}
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Update Build Configuration
      run: |
        echo "📱 Updating build configuration..."
        echo "App Name: ${{ env.APP_NAME }}"
        echo "Package Name: ${{ env.PACKAGE_NAME }}"
        echo "Version Name: ${{ github.event.inputs.version_name }}"
        echo "Version Code: ${{ github.event.inputs.version_code }}"
        echo "Build Type: ${{ github.event.inputs.build_type }}"
        
        # Update build.gradle with version info
        sed -i "s/versionCode .*/versionCode ${{ github.event.inputs.version_code }}/" app/build.gradle
        sed -i "s/versionName .*/versionName \"${{ github.event.inputs.version_name }}\"/" app/build.gradle
        
        # Update AndroidManifest.xml if needed
        # sed -i "s/android:versionCode=\".*\"/android:versionCode=\"${{ github.event.inputs.version_code }}\"/" app/src/main/AndroidManifest.xml
        # sed -i "s/android:versionName=\".*\"/android:versionName=\"${{ github.event.inputs.version_name }}\"/" app/src/main/AndroidManifest.xml
        
    - name: Make gradlew executable
      run: chmod +x gradlew
      
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Build Debug APK
      if: github.event.inputs.build_type == 'debug'
      run: |
        echo "🔨 Building Debug APK..."
        ./gradlew clean assembleDebug --stacktrace --info
        echo "✅ Debug APK build completed!"
        
    - name: Build Release APK
      if: github.event.inputs.build_type == 'release'
      run: |
        echo "🔨 Building Release APK..."
        
        # Create debug keystore for signing
        echo "🔑 Creating debug keystore..."
        mkdir -p ~/.android || true
        keytool -genkeypair \
          -v \
          -keystore ~/.android/debug.keystore \
          -alias androiddebugkey \
          -keyalg RSA \
          -keysize 2048 \
          -validity 10000 \
          -dname "CN=Android Debug,O=Android,C=US" \
          -storepass android \
          -keypass android \
          -keyalg RSA \
          -storetype pkcs12
          
        # Create keystore.properties file
        echo "storePassword=android" > keystore.properties
        echo "keyPassword=android" >> keystore.properties
        echo "keyAlias=androiddebugkey" >> keystore.properties
        echo "storeFile=~/.android/debug.keystore" >> keystore.properties
        
        ./gradlew clean assembleRelease --stacktrace --info
        echo "✅ Release APK build completed!"
        
    - name: List Build Outputs
      run: |
        echo "📁 Build outputs:"
        find app/build/outputs -name "*.apk" -type f | xargs ls -la
        echo ""
        echo "📊 APK Information:"
        for apk in $(find app/build/outputs -name "*.apk" -type f); do
          echo "File: $(basename $apk)"
          echo "Size: $(du -h $apk | cut -f1)"
          echo "Path: $apk"
          echo "---"
        done
        
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: myeye-${{ github.event.inputs.build_type }}-v${{ github.event.inputs.version_name }}
        path: |
          app/build/outputs/apk/${{ github.event.inputs.build_type }}/*.apk
          app/build/outputs/apk/${{ github.event.inputs.build_type }}/output-metadata.json
        retention-days: 30
        
    - name: Generate Build Report
      run: |
        echo "📋 BUILD REPORT" >> $GITHUB_STEP_SUMMARY
        echo "==============" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**App Information:**" >> $GITHUB_STEP_SUMMARY
        echo "- App Name: ${{ env.APP_NAME }}" >> $GITHUB_STEP_SUMMARY
        echo "- Package Name: ${{ env.PACKAGE_NAME }}" >> $GITHUB_STEP_SUMMARY
        echo "- Version Name: ${{ github.event.inputs.version_name }}" >> $GITHUB_STEP_SUMMARY
        echo "- Version Code: ${{ github.event.inputs.version_code }}" >> $GITHUB_STEP_SUMMARY
        echo "- Build Type: ${{ github.event.inputs.build_type }}" >> $GITHUB_STEP_SUMMARY
        echo "- Build Date: $(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        echo "**APK Files:**" >> $GITHUB_STEP_SUMMARY
        for apk in $(find app/build/outputs -name "*.apk" -type f); do
          apk_name=$(basename $apk)
          apk_size=$(du -h $apk | cut -f1)
          echo "- **$apk_name** ($apk_size)" >> $GITHUB_STEP_SUMMARY
        done
        echo "" >> $GITHUB_STEP_SUMMARY
        
        echo "**Download:**" >> $GITHUB_STEP_SUMMARY
        echo "APK files are available in the Artifacts section above." >> $GITHUB_STEP_SUMMARY
        
    - name: Send Success Notification
      if: success()
      run: |
        echo "🎉 APK Build Successful!"
        echo ""
        echo "========================================"
        echo "APP DETAILS:"
        echo "========================================"
        echo "Name: ${{ env.APP_NAME }}"
        echo "Package: ${{ env.PACKAGE_NAME }}"
        echo "Version: ${{ github.event.inputs.version_name }} (Code: ${{ github.event.inputs.version_code }})"
        echo "Build: ${{ github.event.inputs.build_type }}"
        echo "Date: $(date)"
        echo "Commit: ${{ github.sha }}"
        echo "Branch: ${{ github.ref_name }}"
        echo "========================================"
        echo ""
        echo "📦 APK files are available in Artifacts"
        echo "📋 Build report in Summary tab"
        
    - name: Send Failure Notification
      if: failure()
      run: |
        echo "❌ APK Build Failed!"
        echo ""
        echo "Check the build logs for errors."
        echo "Common issues:"
        echo "1. Missing dependencies"
        echo "2. Gradle sync issues"
        echo "3. Build configuration errors"
