name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      
    - name: Build APK
      run: |
        ./gradlew clean
        ./gradlew assembleDebug
        
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: MyEye-App
        path: app/build/outputs/apk/debug/app-debug.apk        ./gradlew clean assembleRelease --stacktrace --info
        echo "✅ Release APK build completed!"
        
    - name: List Build Outputs
      run: |
        echo "📁 Build outputs:"
        find app/build/outputs -name "*.apk" -type f | xargs ls -la
        echo ""
        echo "📊 APK Information:"
        for apk in $(find app/build/outputs -name "*.apk" -type f); do
          echo "File: $(basename $apk)"
          echo "Size: $(du -h $apk | cut -f1)"
          echo "Path: $apk"
          echo "---"
        done
        
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: myeye-${{ github.event.inputs.build_type }}-v${{ github.event.inputs.version_name }}
        path: |
          app/build/outputs/apk/${{ github.event.inputs.build_type }}/*.apk
          app/build/outputs/apk/${{ github.event.inputs.build_type }}/output-metadata.json
        retention-days: 30
        
    - name: Generate Build Report
      run: |
        echo "📋 BUILD REPORT" >> $GITHUB_STEP_SUMMARY
        echo "==============" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**App Information:**" >> $GITHUB_STEP_SUMMARY
        echo "- App Name: ${{ env.APP_NAME }}" >> $GITHUB_STEP_SUMMARY
        echo "- Package Name: ${{ env.PACKAGE_NAME }}" >> $GITHUB_STEP_SUMMARY
        echo "- Version Name: ${{ github.event.inputs.version_name }}" >> $GITHUB_STEP_SUMMARY
        echo "- Version Code: ${{ github.event.inputs.version_code }}" >> $GITHUB_STEP_SUMMARY
        echo "- Build Type: ${{ github.event.inputs.build_type }}" >> $GITHUB_STEP_SUMMARY
        echo "- Build Date: $(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        echo "**APK Files:**" >> $GITHUB_STEP_SUMMARY
        for apk in $(find app/build/outputs -name "*.apk" -type f); do
          apk_name=$(basename $apk)
          apk_size=$(du -h $apk | cut -f1)
          echo "- **$apk_name** ($apk_size)" >> $GITHUB_STEP_SUMMARY
        done
        echo "" >> $GITHUB_STEP_SUMMARY
        
        echo "**Download:**" >> $GITHUB_STEP_SUMMARY
        echo "APK files are available in the Artifacts section above." >> $GITHUB_STEP_SUMMARY
        
    - name: Send Success Notification
      if: success()
      run: |
        echo "🎉 APK Build Successful!"
        echo ""
        echo "========================================"
        echo "APP DETAILS:"
        echo "========================================"
        echo "Name: ${{ env.APP_NAME }}"
        echo "Package: ${{ env.PACKAGE_NAME }}"
        echo "Version: ${{ github.event.inputs.version_name }} (Code: ${{ github.event.inputs.version_code }})"
        echo "Build: ${{ github.event.inputs.build_type }}"
        echo "Date: $(date)"
        echo "Commit: ${{ github.sha }}"
        echo "Branch: ${{ github.ref_name }}"
        echo "========================================"
        echo ""
        echo "📦 APK files are available in Artifacts"
        echo "📋 Build report in Summary tab"
        
    - name: Send Failure Notification
      if: failure()
      run: |
        echo "❌ APK Build Failed!"
        echo ""
        echo "Check the build logs for errors."
        echo "Common issues:"
        echo "1. Missing dependencies"
        echo "2. Gradle sync issues"
        echo "3. Build configuration errors"
